openapi: 3.0.0
info:
  title: VDX Example client
  description: API description for example client..
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk
tags:
  - name: VDXExample
    description: VDX Example API

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:
  /v1/{uuid}:
    get:
      tags:
        - VDXExample
      summary: Call the service that call VideoAPI
      description: Call the service that call VideoAPI.
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exampleResponse'

components:
  parameters:
    uuid:
      name: uuid
      in: path
      description: the uuid for the requested information
      required: true
      schema:
        type: string
        format: uuid
      example: 46b46a1e-a4d3-4387-87ee-a67dcaa222cb
  schemas:
    exampleResponse:
      type: object
      required:
        - subject
        - uuid
        - startTime
        - endTime
        - shortId
      properties:
        subject:
          type: string
          maxLength: 100
          example: Short talk about hiring new people
        uuid:
          type: string
          format: uuid
          example: 46b46a1e-a4d3-4387-87ee-a67dcaa222cb
        startTime:
          type: string
          format: date-time
          example: 2018-11-01T10:00:00+0000
        endTime:
          type: string
          format: date-time
          example: 2018-11-01T10:30:00+0000
        description:
          type: string
          maxLength: 500
          example: We need to agree on the process should be. And what deadlines we have during the next 14 days.
        shortId:
          type: string
          minLength: 12
          maxLength: 12
          example: abcdefghijkl
        shortLink:
          type: string
          example: https://m.vconf.dk/abcdefghijkl
